Configuration_name: 20250121_train_AE
device: 'cuda'

TrainingDataSetConfigs:
  dataset_name: MNIST
  dataset_type: Train
  dataset_path: /media/4T/mit_6s978/data/
  batch_size: 256
  total_epochs: 20

TestingDataSetConfigs:
  dataset_name: MNIST
  dataset_type: Test
  batch_size: 10
  dataset_path: /media/4T/mit_6s978/data/

modelConfigs:
  model_class_name: AutoEncoder
  input_dim: 784 # 28*28
  hidden_dims: [128, 32, 16, 2]
  use_sigmoid: True

optimizerConfigs:
  optimizer_name: Adam
  learning_rate: 1e-2
  weight_decay: 1e-8