Configuration_name: 20250121_train_PointCloudVAE_latentSize16
device: 'cuda'

TrainingDataSetConfigs:
  dataset_name: PointCloudTorus
  dataset_type: Train
  dataset_path: 0
  batch_size: 3000
  total_epochs: 1000
  R: 1.0
  r: 0.5
  num_points: 3000

TestingDataSetConfigs:
  dataset_name: PointCloudTorus
  dataset_type: Test
  batch_size: 1000
  R: 1.0
  r: 0.5
  num_points: 3000
  plot_interval: 100
  dataset_path: 0

modelConfigs:
  model_class_name: PointVAE
  input_dim: 60 # 28*28 + 128
  hidden_dims: [32, 16, 4]
  decode_dim: 2
  reg_coff: 0.001
  conditional: False
  # n_classes: 10
  use_sigmoid: False
  use_torus_latent_code: True

optimizerConfigs:
  optimizer_name: Adam
  learning_rate: 1e-3
  weight_decay: 1e-8