Configuration_name: 20250306_train_AR_PixCnn_CE
device: 'cuda'

TrainingDataSetConfigs:
  dataset_name: MNIST
  dataset_type: Train
  dataset_path: /media/4T/mit_6s978/data/
  batch_size: 768
  total_epochs: 60
  reshape_to_vector: False
  binarize_image: False
  n_classes: 10
  Normalize: False

TestingDataSetConfigs:
  dataset_name: MNIST
  dataset_type: Test
  batch_size: 64
  dataset_path: /media/4T/mit_6s978/data/
  validation_interval: 5
  reshape_to_vector: False
  binarize_image: False
  n_classes: 10
  Normalize: False

modelConfigs:
  model_class_name: PixelCNN
  conditional: True
  input_chn: 1
  num_ResMasked_conv: 4
  inner_chn: 64
  output_chn: 256
  pixelcnn_useSigmoid: False
  save_model_interval: 5


optimizerConfigs:
  optimizer_name: Adam
  learning_rate: 1e-3